### ISSUE TITLE
Visualization is not working!

### ISSUE THREAD

**Issue by andwine** [P7h/StormTweetsSentimentD3UKViz#1]
Hello, 

Thank you very much for sharing your source code. I really appreciate it. 
When I click 'start viz' button, nothing happens. Otherwise, everything is very good.

Could you check it out?

Thanks,
Best Regards,
Sang

**Comment by sbnair** [comment]
Hi,

  For me i am getting the tweets in the command prompt but i am not getting visualization ,i tried in firefox and chrome browser,please help.

Thanks,
Shailesh.

**Comment by andwine** [comment]
Hello,


Yes, I have exactly same thing happened. Could you help us?


Best Regards,

Sangwhan Cha

________________________________

**Comment by P7h** [comment]
Hi Shailesh and Sangwhan,

I tested the app in local mode now. Visualization worked perfectly fine for me.

* Are you running the app in local mode or cluster mode?
* Did you setup Google Maps key properly? As mentioned in the README, this key has to be configured in [config.properties] (https://github.com/P7h/StormTweetsSentimentD3UKViz/blob/master/src/main/resources/config.properties#L11). Please check the corresponding comments there for more info on setting up Google Maps keys.
* And it can be easily verified by adding a debug statement in [StateLocator.java](https://github.com/P7h/StormTweetsSentimentD3UKViz/blob/master/src/main/java/org/p7h/storm/sentimentanalysis/bolts/StateLocatorBolt.java#L74) after line#74. Is the debug statement giving you a proper state?
* You need to launch a command window in viz folder and run SimpleHTTPServer. If the visualization does n't work, what does it show in Chrome Dev Tools [press F12 in Chrome once you see the tweets are coming fine and state locator also is working]?

Regards,
Prashanth.

**Comment by andwine** [comment]
?Hello Prashanth,


Thank you very much for helping us very quickly. I really appreciated it.

I think that I am still using Bing Map same as the second example. I will use the google map as you mentioned.

I think that it will work if I use Google Map this time.


Once again, Thank you very much,

Have a great weekend,

Best Regards,

Sangwhan Cha

________________________________

**Comment by P7h** [comment]
Hi Sangwhan,

Bing Maps could hardly reverse geocode for UK. I have mentioned the motive behind choosing Google Maps API for this repo in the [Features](https://github.com/P7h/StormTweetsSentimentD3UKViz#features) section of README.

> Just for the perspective, Bing Maps could convert only 3 out of 400 latlong requests to a location. While Google Maps API converted almost 95% of the latlong requests to a location.

If you use Google Maps API, your visualization should appear fine.
Let me know if you face any further issues.

Wish you too a great weekend.

Regards,
Prashanth.

**Comment by P7h** [comment]
Hi Shailesh and Sangwhan,

Hope you guys were able to launch and view the visualization properly.
Please let me know if in case you are facing issues even after following all the instructions properly.
If all fine, please close this issue.

Regards,
Prashanth.

**Comment by andwine** [comment]
Hello Prashanth,


Sure, I will close my issue. Thank you very much for your effort for your open source.

?I really appreciate it.


Have a great weekend,

Best Regards,

Sangwhan

________________________________

**Comment by P7h** [comment]
Thanks Sangwhan.
Also, just checking, were you able to get the visualization working on your env / machine?

**Comment by andwine** [comment]
?Sure, It works very well.


Thank you very much,

Best Regards,

Sangwhan


________________________________

**Comment by P7h** [comment]
Brilliant. ATB!
